config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :movies, dependent: :restrict_with_error
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client, optional: true
  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.order(:id)
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  

  def destroy
    if @client.destroy
      respond_to do |format|
        format.html { redirect_to clients_url, notice: "Cliente eliminado" }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to client_url, notice: "No se puede eliminar el cliente porque tiene películas asociadas" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :set_clients, only: %i[ new edit create destroy update]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_clients
      @clients = Client.all.pluck :name, :id
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :client_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <tr style= "text-decoration: none; color: white;">
    <th scope="row"><%= client.id %></th>
    <td><%= client.name %></td>
    <td><%= client.age %></td>
    <td><%= client.movies.last %></td>
    <td><%= link_to "Show this client", client, class: "btn btn-primary" %></td>
    <td><%= link_to "Edit this client", edit_client_path(client), class: "btn btn-primary" %></td>
    <!--<td><%= button_to "Destroy this client", @client, method: :delete %></td>
    -->
  </tr>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1 class="mt-5">Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client, class: "btn btn-primary"  %> |
  <%= link_to "Back to clients", clients_path, class: "btn btn-primary"  %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Clients</h1>

  <%= link_to "New client", new_client_path, class: "btn btn-primary mb-2" %>



  <div id="clients">
    <table class="table table-bordered">
      <thead>
        <tr style="text-align: center; color:white">
          <th scope="col">#</th>
          <th scope="col">Nombre</th>
          <th scope="col">Edad</th>
          <th scope="col">Movie</th>
          <th scope="col" colspan="3"> Opciones</th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <%= render client %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="text-left border rounded-2 mt-5 text-white h5">

    <div class="row ps-2 mt-5 ">
      <div class="col-2">
        Id
      </div>
      <div class="col-1">
        <%= @client.id %>
      </div>
    </div>

    <div class="row ps-2">
      <div class="col-2">
        Nombre
      </div>
      <div class="col-6">
        <%= @client.name %>
      </div>
    </div>

    <div class="row ps-2">
      <div class="col-2">
        Edad
      </div>
      <div class="col-6">
        <%= @client.age %>
      </div>
    </div>

    <div class="row ps-2">
      <div class="col-2">
        Película arrendada
      </div>
      <div class="col-6">
        <%= @client.movies.last %>
      </div>
    </div>
  </div>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) , class: "btn btn-primary mt-2" %> |
  <%= link_to "Back to clients", clients_path , class: "btn btn-primary mt-2" %>

  <%= button_to "Destroy this client", @client,class: "btn btn-danger mt-2" , method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>

  <body style="background-color: #0e68a7">
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: rgba(5,44,101,255);">
  <div class="container">
    <a class="navbar-brand text-light" href="<%= pages_index_path %>">
    <img src="<%= image_path('logo_blockbuster.png') %>" alt="Blockbuster Logo" class="logo" style="width: 70px;">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-light" href="<%= clients_path %>">Clientes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="<%= movies_path %>">Películas</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <div class="container">
      <%= yield %>
      <footer class="text-center mt-5">
        <a href="<%= pages_index_path%>">
          <img src="<%= image_path('logo_blockbuster.png') %>" alt="Blockbuster Logo" class="mb-4 logo" style="width: 250px;">
        </a>
        <p>&copy; 2024 Blockbuster. Todos los derechos reservados. Esta página está dedicada a la alquilación de películas clásicas y modernas. ¡Explora nuestra colección y disfruta de tus películas favoritas!</p>
      </footer>
    </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.select :client_id, options_for_select(@clients) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
  <div class="col-4 py-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= movie.name %></h5>
        <%= link_to "Show this movie", movie, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Movies</h1>
  <%= link_to "New movie", new_movie_path, class: "btn btn-primary"  %>
  <div id="movies">
    <div class="row">
      <% @movies.each do |movie| %>
        <%= render movie %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
, class: "btn btn-primary" <p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie), class: "btn btn-primary mt-2"  %> |
  <%= link_to "Back to movies", movies_path, class: "btn btn-primary mt-2"  %>

  <%= button_to "Destroy this movie", @movie, method: :delete, class: "btn btn-danger mt-2" %>
</div>

app/views/pages/index.html.erb
<body>
<div class="container" style="margin-top: 80px; text-align: center; background-color: rgba(31, 139, 185, 0.8); padding: 10px; border-radius: 15px;">
  <h1 class="mt-5">Bienvenido a la Página de Alquiler de Películas</h1>

  <div class="mt-4">
    <div class="d-flex justify-content-center">
      <a href="<%= clients_path %>" class="btn btn-primary mx-2">Ver Clientes</a>
      <a href="<%= movies_path %>" class="btn btn-primary mx-2">Ver Películas</a>
    </div>
  </div>
</div>



<div class="container mt-5 text-center">
  
  <div id="carouselExampleIndicators" class="carousel slide mb-4" data-ride="carousel">
  <div class="carousel-inner text-center">
    <div class="carousel-item active">
      <img src="<%= image_path('imagen1.jpg') %>" class="d-block mx-auto rounded" style="width: 700px; height: 500px;" alt="Imagen 1">
    </div>
    <div class="carousel-item">
      <img src="<%= image_path('imagen2.jpg') %>" class="d-block mx-auto rounded" style="width: 700px; height: 500px;" alt="Imagen 2">
    </div>
    <div class="carousel-item">
      <img src="<%= image_path('imagen3.jpg') %>" class="d-block mx-auto rounded" style="width: 700px; height: 500px;" alt="Imagen 3">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Siguiente</span>
  </a>
  
</div>

  
</body>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'BlockBuster', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Clients', clients_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Movies', movies_path, class: 'nav-link' %>
        </li>
    </div>
  </div>
</nav>